language: python
sudo: false
env:
    - PYTHON_VERSION=3.5
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # Install qiita
  - travis_retry conda create --yes -n qiita python=2.7 pip nose flake8
    pyzmq networkx pyparsing natsort mock future libgfortran
    'pandas>=0.18' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate qiita
  - pip install sphinx sphinx-bootstrap-theme coveralls ipython[all]==2.4.1
  - pip install https://github.com/biocore/qiita/archive/analysis-refactor.zip --process-dependency-links
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/server.crt
  - export MOI_CONFIG_FP=$HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg
  - ipython profile create qiita-general --parallel
  - qiita-env start_cluster qiita-general
  - qiita-env make --no-load-ontologies
  - source deactivate
  # Install the plugin
  - travis_retry conda create --yes -n qtp-visualization python=$PYTHON_VERSION --file https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-conda-linux-64.txt
  - source activate qtp-visualization
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - pip install coveralls
  - travis_retry pip install . --process-dependency-links
  - configure_visualization_types --env-script "source activate qtp-visualization" --server-cert $QIITA_SERVER_CERT
before_script:
  - source activate qiita
  - qiita plugins update
  - qiita pet webserver --no-build-docs start &
script:
  - source activate qtp-visualization
  - sleep 5 # give enough time to the webserver to start
  - nosetests --with-doctest --with-coverage -v --cover-package=qtp_visualization
  - flake8 qtp_visualization setup.py scripts
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - coveralls
